### ISSUE TITLE
The output result has no information

### ISSUE THREAD

**Issue by yuezhiTang** [gamcil/clinker#101]
I installed clinker using conda and confirmed successful installation, but no matter how many antismash output .gbk files I used for visualization, it did not succeed. The data I use may come directly from the antismash results of a single species (about 50), or from gene clusters clustered together through bigscape clustering (about 5), or from samples with high similarity in gene cluster information stored in the mibig database (about 2). But the final generated .html files did not have visual results. At the same time, I added the command - o demo.txt without any output. May I ask what is the cause or what are the solutions?
Sincerely looking forward to receiving your reply

(clinker) [xx@mu01 demo3]$ clinker files/*.gbk -p demo.html
[22:26:20] INFO - Starting clinker
[22:26:20] INFO - Opening empty clinker web app...
[22:26:20] INFO - Parsing files:
[22:26:20] INFO - Starting cluster alignments
[22:26:20] INFO - No alignments were generated
[22:26:20] INFO - Building clustermap.js visualisation
[22:26:20] INFO - Writing to: demo.html
[22:26:20] INFO - Done!

or

[23:08:12] INFO - Starting clinker
[23:08:12] INFO - Parsing files:
[23:08:12] INFO -   contig1_pilon.region001.gbk
[23:08:12] WARNING - Could not find parent gene of <unknown id>. Using coding sequence coordinates instead.
[23:08:12] WARNING - Could not find parent gene of <unknown id>. Using coding sequence coordinates instead.
[23:08:12] WARNING - Could not find parent gene of <unknown id>. Using coding sequence coordinates instead.
[23:08:12] WARNING - Could not find parent gene of <unknown id>. Using coding sequence coordinates instead.
[23:08:12] WARNING - Could not find parent gene of <unknown id>. Using coding sequence coordinates instead.
[23:08:12] WARNING - Could not find parent gene of <unknown id>. Using coding sequence coordinates instead.
[23:08:12] WARNING - Could not find parent gene of <unknown id>. Using coding sequence coordinates instead.
[23:08:12] WARNING - Could not find parent gene of <unknown id>. Using coding sequence coordinates instead.
[23:08:12] WARNING - Could not find parent gene of <unknown id>. Using coding sequence coordinates instead.
[23:08:12] WARNING - Could not find parent gene of <unknown id>. Using coding sequence coordinates instead.
[23:08:12] WARNING - Could not find parent gene of <unknown id>. Using coding sequence coordinates instead.
[23:08:12] WARNING - Could not find parent gene of <unknown id>. Using coding sequence coordinates instead.
[23:08:12] WARNING - Could not find parent gene of <unknown id>. Using coding sequence coordinates instead.
[23:08:12] WARNING - Could not find parent gene of <unknown id>. Using coding sequence coordinates instead.
[23:08:12] WARNING - Could not find parent gene of <unknown id>. Using coding sequence coordinates instead.
[23:08:12] WARNING - Could not find parent gene of <unknown id>. Using coding sequence coordinates instead.
[23:08:12] WARNING - Could not find parent gene of <unknown id>. Using coding sequence coordinates instead.
[23:08:12] WARNING - Could not find parent gene of <unknown id>. Using coding sequence coordinates instead.
[23:08:12] WARNING - Could not find parent gene of <unknown id>. Using coding sequence coordinates instead.
[23:08:12] WARNING - Could not find parent gene of <unknown id>. Using coding sequence coordinates instead.
[23:08:12] WARNING - Could not find parent gene of <unknown id>. Using coding sequence coordinates instead.
[23:08:12] INFO -   contig1_pilon.region002.gbk
Traceback (most recent call last):
  File "/home/xx/miniconda3/envs/clinker/lib/python3.11/site-packages/Bio/File.py", line 72, in as_handle
    with open(handleish, mode, **kwargs) as fp:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: expected str, bytes or os.PathLike object, not TextIOWrapper

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xx/miniconda3/envs/clinker/bin/clinker", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/xx/miniconda3/envs/clinker/lib/python3.11/site-packages/clinker/main.py", line 353, in main
    clinker(
  File "/home/xx/miniconda3/envs/clinker/lib/python3.11/site-packages/clinker/main.py", line 167, in clinker
    clusters = parse_files(paths, ranges=ranges, set_origin=set_origin)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xx/miniconda3/envs/clinker/lib/python3.11/site-packages/clinker/classes.py", line 329, in parse_files
    cluster = cluster_from_genbank(path, ranges=ranges, set_origin=set_origin)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xx/miniconda3/envs/clinker/lib/python3.11/site-packages/clinker/classes.py", line 299, in cluster_from_genbank
    for record in SeqIO.parse(fp, "genbank"):
  File "/home/xx/miniconda3/envs/clinker/lib/python3.11/site-packages/Bio/SeqIO/Interfaces.py", line 72, in __next__
    return next(self.records)
           ^^^^^^^^^^^^^^^^^^
  File "/home/xx/miniconda3/envs/clinker/lib/python3.11/site-packages/Bio/GenBank/Scanner.py", line 516, in parse_records
    record = self.parse(handle, do_features)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xx/miniconda3/envs/clinker/lib/python3.11/site-packages/Bio/GenBank/Scanner.py", line 499, in parse
    if self.feed(handle, consumer, do_features):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xx/miniconda3/envs/clinker/lib/python3.11/site-packages/Bio/GenBank/Scanner.py", line 465, in feed
    self._feed_first_line(consumer, self.line)
  File "/home/xx/miniconda3/envs/clinker/lib/python3.11/site-packages/Bio/GenBank/Scanner.py", line 1424, in _feed_first_line
    raise ValueError(
ValueError: LOCUS line does not contain valid entry (linear, circular, ...):
LOCUS       contig1_pilon_re       30640 bp    DNA        linear       27-JUL-2023

![QQ截图20231016223854](https://github.com/gamcil/clinker/assets/142855548/59f10aab-e222-4ae7-ba2e-eef3cf594100)

**Comment by gamcil** [comment]
Hi @yuezhiTang, is it possible to upload any of the files you used here?

**Comment by yuezhiTang** [comment]
> Hi @yuezhiTang, is it possible to upload any of the files you used here?

Thank you for your reply. I have reviewed the instructions and found that it was an error in my use. The results have now been generated.

**Comment by yuezhiTang** [comment]
> Hi @yuezhiTang Please explain briefly what was the error, and how you fix it. Your mistake can be other's mistake as well =)

This problem has been going on for too long, and the specific reason for the error is probably that the command line I used at that time may not be correct. As long as the user follows the correct usage method, the error will basically not occur.

**Comment by chrisharper-stl** [comment]
> Hi [@yuezhiTang](https://github.com/yuezhiTang) Please explain briefly what was the error, and how you fix it. Your mistake can be other's mistake as well =)

Whenever I've run into this issue, it's usually because I'm in the wrong directory and thus the directory I'm telling it to look in for input files relative to my working directory doesn't exist. Hopefully this helps someone in the future.
