### ISSUE TITLE
ValueError: sequence contains letters not in the alphabet

### ISSUE THREAD

**Issue by Akllarena** [gamcil/clinker#11]
Hei!
I wanted to try out clinker, which is something that ive been longing for. I downloaded som gbff from ncbi, even renamed them gbk, but I get an error (header, and bottom). I havent done a thing with these, so howcome it doesnt work? Is there an open limit to genome size? These are mostly 5.5 Mb? Or is it not suitable for procaryotes?

(base) [annll@login ncbi-genomes-2020-11-16]$ ls
GCF_000003955.1_ASM395v1_genomic.gbk    GCF_000497525.1_ASM49752v2_genomic.gbk   GCF_002000005.1_ASM200000v1_genomic.gbk  GCF_004119835.1_ASM411983v1_genomic.gbk
GCF_000008005.1_ASM800v1_genomic.gbk    GCF_000832865.1_ASM83286v1_genomic.gbk   GCF_002582095.1_ASM258209v1_genomic.gbk  GCF_007682195.1_ASM768219v1_genomic.gbk
GCF_000161175.1_ASM16117v1_genomic.gbk  GCF_001044825.1_ASM104482v1_genomic.gbk  GCF_003426125.1_ASM342612v1_genomic.gbk  md5checksums.txt
GCF_000161395.1_ASM16139v1_genomic.gbk  GCF_001704095.1_ASM170409v1_genomic.gbk  GCF_003612955.1_ASM361295v1_genomic.gbk  README.txt
GCF_000186745.1_ASM18674v1_genomic.gbk  GCF_001721165.1_ASM172116v1_genomic.gbk  GCF_004101345.1_ASM410134v1_genomic.gbk
(base) [annll@login ncbi-genomes-2020-11-16]$ clinker *.gbk
[12:06:03] INFO - Starting clinker
[12:06:03] INFO - Parsing GenBank files: ['GCF_000003955.1_ASM395v1_genomic.gbk', 'GCF_000008005.1_ASM800v1_genomic.gbk', 'GCF_000161175.1_ASM16117v1_genomic.gbk', 'GCF_000161395.1_ASM16139v1_                                             genomic.gbk', 'GCF_000186745.1_ASM18674v1_genomic.gbk', 'GCF_000497525.1_ASM49752v2_genomic.gbk', 'GCF_000832865.1_ASM83286v1_genomic.gbk', 'GCF_001044825.1_ASM104482v1_genomic.gbk', 'GCF_0017                                             04095.1_ASM170409v1_genomic.gbk', 'GCF_001721165.1_ASM172116v1_genomic.gbk', 'GCF_002000005.1_ASM200000v1_genomic.gbk', 'GCF_002582095.1_ASM258209v1_genomic.gbk', 'GCF_003426125.1_ASM342612v1_                                             genomic.gbk', 'GCF_003612955.1_ASM361295v1_genomic.gbk', 'GCF_004101345.1_ASM410134v1_genomic.gbk', 'GCF_004119835.1_ASM411983v1_genomic.gbk', 'GCF_007682195.1_ASM768219v1_genomic.gbk']
/mnt/users/annll/.local/lib/python3.7/site-packages/Bio/Seq.py:2338: BiopythonWarning: Partial codon, len(sequence) not a multiple of three. Explicitly trim the sequence or add trailing N befo                                             re translation. This may become an error in future.
  BiopythonWarning,
[12:06:29] INFO - Starting cluster alignments
[12:06:29] INFO - GCF_000003955.1_ASM395v1_genomic vs GCF_000008005.1_ASM800v1_genomic
Traceback (most recent call last):
  File "/mnt/users/annll/.local/bin/clinker", line 11, in <module>
    sys.exit(main())
  File "/mnt/users/annll/.local/lib/python3.7/site-packages/clinker/main.py", line 153, in main
    hide_alignment_headers=args.hide_aln_headers,
  File "/mnt/users/annll/.local/lib/python3.7/site-packages/clinker/main.py", line 56, in clinker
    globaligner = align.align_clusters(*clusters, cutoff=identity)
  File "/mnt/users/annll/.local/lib/python3.7/site-packages/clinker/align.py", line 51, in align_clusters
    aligner.align_stored_clusters(cutoff)
  File "/mnt/users/annll/.local/lib/python3.7/site-packages/clinker/align.py", line 240, in align_stored_clusters
    alignment = self.align_clusters(one, two, cutoff)
  File "/mnt/users/annll/.local/lib/python3.7/site-packages/clinker/align.py", line 227, in align_clusters
    aln = self.aligner.align(geneA.translation, geneB.translation)
  File "/mnt/users/annll/.local/lib/python3.7/site-packages/Bio/Align/__init__.py", line 1592, in align
    score, paths = _aligners.PairwiseAligner.align(self, seqA, seqB)
ValueError: sequence contains letters not in the alphabet
(base) [annll@login ncbi-genomes-2020-11-16]$

**Comment by gamcil** [comment]
Hi, though there isn't a size limit, I really only designed the tool for visualising relatively small gene clusters (e.g. secondary metabolite biosynthetic gene clusters from fungi). That said, it should still work even if it takes ages (there's no parallelisation, so it will align every protein one by one). I think the error you're having here is because clinker is reading in and translating pseudo genes, which GCF_000003955.1_ASM395v1_genomic seems to have a lot of. I'm adding in a check which should fix this issue soon.

**Comment by gamcil** [comment]
Hopefully should work with the newest release (v0.0.6). Could you try upgrading clinker (`pip install --upgrade clinker`) and running it again?

**Comment by Akllarena** [comment]
Thanks, I did, but still got the same errors:

[08:21:28] INFO - Starting clinker
[08:21:28] INFO - Parsing GenBank files: ['GCF_000003955.1_ASM395v1_genomic.gbk', 'GCF_000008005.1_ASM800v1_genomic.gbk', 'GCF_000161175.1_ASM16117v1_genomi$
[08:21:54] INFO - Starting cluster alignments
[08:21:54] INFO - GCF_000003955.1_ASM395v1_genomic vs GCF_000008005.1_ASM800v1_genomic
Traceback (most recent call last):
  File "/mnt/users/annll/.local/bin/clinker", line 8, in <module>
    sys.exit(main())
  File "/mnt/users/annll/.local/lib/python3.7/site-packages/clinker/main.py", line 164, in main
    hide_alignment_headers=args.hide_aln_headers,
  File "/mnt/users/annll/.local/lib/python3.7/site-packages/clinker/main.py", line 60, in clinker
    globaligner = align.align_clusters(*clusters, cutoff=identity)
  File "/mnt/users/annll/.local/lib/python3.7/site-packages/clinker/align.py", line 51, in align_clusters
    aligner.align_stored_clusters(cutoff)
  File "/mnt/users/annll/.local/lib/python3.7/site-packages/clinker/align.py", line 240, in align_stored_clusters
    alignment = self.align_clusters(one, two, cutoff)
  File "/mnt/users/annll/.local/lib/python3.7/site-packages/clinker/align.py", line 227, in align_clusters
    aln = self.aligner.align(geneA.translation, geneB.translation)
  File "/mnt/users/annll/.local/lib/python3.7/site-packages/Bio/Align/__init__.py", line 1592, in align
    score, paths = _aligners.PairwiseAligner.align(self, seqA, seqB)
ValueError: sequence contains letters not in the alphabet

?

**Comment by apcamargo** [comment]
I'm getting the same error with [this genome](https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/015/680/045/GCF_015680045.1_ASM1568004v1/GCF_015680045.1_ASM1568004v1_genomic.gbff.gz).

**Comment by pmvidigal** [comment]
Hi, I'm getting a similar error using annotated genbank files of fungal mitochondrial genomes (codon table 4):
======
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "~/.conda/envs/clinker/lib/python3.9/multiprocessing/pool.py", line 125, in worker
      result = (True, func(*args, **kwds))
  File "~/.conda/envs/clinker/lib/python3.9/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "~/.conda/envs/clinker/lib/python3.9/site-packages/clinker/align.py", line 355, in _align_clusters
    aln = aligner.align(geneA.translation, geneB.translation)
  File "~/.conda/envs/clinker/lib/python3.9/site-packages/Bio/Align/__init__.py", line 1592, in align
    score, paths = _aligners.PairwiseAligner.align(self, seqA, seqB)
ValueError: sequence contains letters not in the alphabet
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "~/.conda/envs/clinker/bin/clinker", line 8, in <module>
    sys.exit(main())
  File "~/.conda/envs/clinker/lib/python3.9/site-packages/clinker/main.py", line 230, in main
    clinker(
  File "~/.conda/envs/clinker/lib/python3.9/site-packages/clinker/main.py", line 93, in clinker
    globaligner = align.align_clusters(*clusters, cutoff=identity, jobs=jobs)
  File "~/.conda/envs/clinker/lib/python3.9/site-packages/clinker/align.py", line 57, in align_clusters
    aligner.align_stored_clusters(cutoff, jobs=jobs)
  File "~/.conda/envs/clinker/lib/python3.9/site-packages/clinker/align.py", line 382, in align_stored_clusters
    alignments = pool.starmap(_align_clusters, pairs_to_align)
  File "~/.conda/envs/clinker/lib/python3.9/multiprocessing/pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "~/.conda/envs/clinker/lib/python3.9/multiprocessing/pool.py", line 771, in get
    raise self._value
ValueError: sequence contains letters not in the alphabet
======

Does clinker translate the CDS or parse the translations available at GenBank files?

**Comment by gamcil** [comment]
The issue seems to be that the sequence aligner from BioPython that clinker uses will throw this error when it finds a letter in the sequences that is not found in the substitution matrix. By default, clinker uses the BLOSUM62 matrix, which does not include extended IUPAC codes (e.g. U), thus causing the issue when it finds them in your sequences. I've just made a change (https://github.com/gamcil/clinker/pull/55) which adds the extended codes to the matrix before alignment, which will be in the next release.

**Comment by pmvidigal** [comment]
Thanks for fixing it! I have found some additional "-" (gaps) on my genbank files and reviewed it. Now its working! Congratulations for its amazing tool that you have developed!

**Comment by gamcil** [comment]
Glad it's working for you. Closing this issue now that v0.0.20 is released.
