### ISSUE TITLE
Error comparing .gbk files outputted from artemis

### ISSUE THREAD

**Issue by kw2990** [gamcil/clinker#7]
Hi,

We're really interested in using your software, but a lot of our gbk files have been created in artemis which often causes problems when moving to other software. We have been able to successfully compare gbk files downloaded from MiBIG, so the installation of clinker is working. When we try to compare artemis generated files we get the following error:

C:\Users\kw2990\University of Bristol\grp-LSB-NSP - Documents\Writing\Reviews\3. Maleidride review\Maleidride bioinformatics\Maleidride clusters>clinker Oidmal.gbk Cadophora.gbk -p
[15:13:51] INFO - Starting clinker
[15:13:51] INFO - Parsing GenBank files: ['Oidmal.gbk', 'Cadophora.gbk']
[15:13:51] INFO - Starting cluster alignments
[15:13:51] INFO - Oidmal vs Cadophora
[15:13:51] INFO - Generating results summary...
Oidmal vs Cadophora
-------------------
Query  Target  Identity  Similarity
[15:13:51] INFO - Building clustermap.js visualisation
C:\Users\kw2990\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\clinker\align.py:356: RuntimeWarning: invalid value encountered in true_divide
  matrix /= matrix.max()
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1776.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1776.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\kw2990\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\Scripts\clinker.exe\__main__.py", line 7, in <module>
  File "C:\Users\kw2990\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\clinker\main.py", line 144, in main
    clinker(
  File "C:\Users\kw2990\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\clinker\main.py", line 77, in clinker
    plot_clusters(globaligner, output=None if plot is True else plot)
  File "C:\Users\kw2990\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\clinker\plot.py", line 114, in plot_clusters
    data = clusters.to_data()
  File "C:\Users\kw2990\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\clinker\align.py", line 201, in to_data
    for i in self.order(i=i, method=method)
  File "C:\Users\kw2990\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\clinker\align.py", line 371, in order
    linkage = hierarchy.linkage(squareform(matrix), method=method)
  File "C:\Users\kw2990\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\scipy\spatial\distance.py", line 2184, in squareform
    is_valid_dm(X, throw=True, name='X')
  File "C:\Users\kw2990\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\scipy\spatial\distance.py", line 2259, in is_valid_dm
    raise ValueError(('Distance matrix \'%s\' must be '
ValueError: Distance matrix 'X' must be symmetric.

I have attached the two files in question as a zipped file
[Sequences.zip](https://github.com/gamcil/clinker/files/5511479/Sequences.zip)

Thanks in advance for any help provided!

**Comment by kw2990** [comment]
Actually, I think we have solved the problem using your answer to the 'Valid CDS identifier?' issue raised previously. We've tended to use /label as a qualifier in artemis.

Thank you for developing this software, it's amazing!
