### ISSUE TITLE
ERROR in matrix.select

### ISSUE THREAD

**Issue by dooguypapua** [gamcil/clinker#75]
$ clinker *.gbk

/usr/local/lib/python3.8/dist-packages/Bio/Align/substitution_matrices/__init__.py:16: BiopythonExperimentalWarning: Bio.Align.substitution_matrices is an experimental module which may still undergo significant changes. In particular, the location of this module may change, and the Array class defined in this module may be moved to other existing or new modules in Biopython.
  warnings.warn("Bio.Align.substitution_matrices is an experimental module "
[17:33:05] INFO - Starting clinker
[17:33:05] INFO - Parsing files:
[17:33:05] INFO -   A. alliaceus CBS 536.65.gbk
[17:33:05] INFO -   A. burnettii MST-FP2249.gbk
/usr/local/lib/python3.8/dist-packages/Bio/Seq.py:2855: BiopythonWarning: Partial codon, len(sequence) not a multiple of three. Explicitly trim the sequence or add trailing N before translation. This may become an error in future.
  warnings.warn(
[17:33:05] INFO -   A. mulundensis DSM 5745.gbk
[17:33:05] INFO -   A. versicolor CBS 583.65.gbk
[17:33:05] INFO -   P. vexata CBS 129021.gbk
[17:33:05] INFO - Starting cluster alignments
[17:33:06] INFO - A. alliaceus CBS 536.65 vs A. mulundensis DSM 5745
[17:33:06] INFO - A. alliaceus CBS 536.65 vs A. burnettii MST-FP2249
[17:33:06] INFO - A. alliaceus CBS 536.65 vs A. versicolor CBS 583.65
[17:33:06] INFO - A. alliaceus CBS 536.65 vs P. vexata CBS 129021
[17:33:06] INFO - A. burnettii MST-FP2249 vs A. mulundensis DSM 5745
[17:33:06] INFO - A. burnettii MST-FP2249 vs A. versicolor CBS 583.65
[17:33:06] INFO - A. burnettii MST-FP2249 vs P. vexata CBS 129021
[17:33:06] INFO - A. mulundensis DSM 5745 vs A. versicolor CBS 583.65
[17:33:06] INFO - A. mulundensis DSM 5745 vs P. vexata CBS 129021
[17:33:06] INFO - A. versicolor CBS 583.65 vs P. vexata CBS 129021
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/usr/local/lib/python3.8/dist-packages/clinker/align.py", line 368, in _align_clusters
    aligner.substitution_matrix = extend_matrix_alphabet(
  File "/usr/local/lib/python3.8/dist-packages/clinker/align.py", line 156, in extend_matrix_alphabet
    matrix = matrix.select(matrix.alphabet + missing_codes)
AttributeError: 'Array' object has no attribute 'select'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/clinker", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/clinker/main.py", line 283, in main
    clinker(
  File "/usr/local/lib/python3.8/dist-packages/clinker/main.py", line 135, in clinker
    globaligner = align.align_clusters(*clusters, cutoff=identity, jobs=jobs)
  File "/usr/local/lib/python3.8/dist-packages/clinker/align.py", line 57, in align_clusters
    aligner.align_stored_clusters(cutoff, jobs=jobs)
  File "/usr/local/lib/python3.8/dist-packages/clinker/align.py", line 415, in align_stored_clusters
    alignments = pool.starmap(_align_clusters, pairs_to_align)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
AttributeError: 'Array' object has no attribute 'select'

**Comment by gamcil** [comment]
Hi, this occurs with versions of BioPython older than 1.78. Could you please try upgrading to the latest version with:

``pip install --upgrade biopython``

and then try clinker again?

The minimum BioPython version has been raised to 1.78 (22fce52fa3b9787e711bbd7dc811055ed1300f24) so future installations should point to the right version.
