### ISSUE TITLE
How to load a session file ?

### ISSUE THREAD

**Issue by lireo** [gamcil/clinker#78]
Hello,

I ran clinker few weeks ago and save it to a session file with -s option. But I can't reload this session file to change some graphic details for publication.

I try with only -s option but clinker don't see the file:
```
clinker -s clinker.json 
[11:05:21] INFO - Starting clinker
[11:05:21] INFO - No files provided!
```

I try with -s and -p but the plot is empty:
```
clinker -s clinker.json -p
[11:10:03] INFO - Starting clinker
[11:10:03] INFO - No files provided!
[11:10:03] INFO - Opening empty clinker web app...
[11:10:03] INFO - Serving clinker plot at http://127.0.0.1:55559/ (Ctrl+C to stop).
```

I try to add gbk file but I  have an error message:

```
clinker -s clinker.json TG6P_CIRM336.gbk TG6P_JIM10116.gbk
[11:16:21] INFO - Starting clinker
[11:16:21] INFO - Loading session from: clinker.json
Traceback (most recent call last):
  File "/Users/aurelie/anaconda3/envs/clinker/bin/clinker", line 10, in <module>
    sys.exit(main())
  File "/Users/aurelie/anaconda3/envs/clinker/lib/python3.10/site-packages/clinker/main.py", line 322, in main
    clinker(
  File "/Users/aurelie/anaconda3/envs/clinker/lib/python3.10/site-packages/clinker/main.py", line 128, in clinker
    globaligner = align.Globaligner.from_json(fp)
  File "/Users/aurelie/anaconda3/envs/clinker/lib/python3.10/site-packages/clinker/classes.py", line 311, in from_json
    return cls.from_dict(d)
  File "/Users/aurelie/anaconda3/envs/clinker/lib/python3.10/site-packages/clinker/align.py", line 253, in from_dict
    for cluster_uid in d["order"]:
KeyError: 'order'
```

I'm desperate and thank you in advance for any help you can give me.

**Comment by gamcil** [comment]
Hi, sorry for the late response. Is it possible to upload your session file for me to try?

**Comment by lireo** [comment]
Hi

I found a solution. I lunch an empty clinker instance and load json after in the navigator.

I forgot to post it and close my issue.
