### ISSUE TITLE
update 0.0.28

### ISSUE THREAD

**Issue by oclaisse** [gamcil/clinker#94]
Hello, I have installed clinker with conda create -n clinker -c conda-forge -c bioconda clinker-py
I have try to update to v0.0.28 because I have some errors when I want to compare some genomes:
but it stay on clinker v0.0.26 I don't no if it can solve the below issue:
if it due to the size of sequences, or because they are in different contigs,  because, I have no problem with phage genomes

"multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/claisse/anaconda3/envs/clinker/lib/python3.11/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
                    ^^^^^^^^^^^^^^^^^^^
  File "/home/claisse/anaconda3/envs/clinker/lib/python3.11/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/claisse/anaconda3/envs/clinker/lib/python3.11/site-packages/clinker/align.py", line 390, in _align_clusters
    aln = aligner.align(geneA.translation.strip(),
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/claisse/anaconda3/envs/clinker/lib/python3.11/site-packages/Bio/Align/__init__.py", line 3121, in align
    score, paths = _aligners.PairwiseAligner.align(self, sA, sB, strand)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: sequence contains letters not in the alphabet

Best regards
Olivier

**Comment by gamcil** [comment]
Hi Olivier, is it possible to upload one of your input files so I can have a look?

**Comment by oclaisse** [comment]
[NRIC649.txt](https://github.com/gamcil/clinker/files/10330659/NRIC649.txt)
[DSM17330.txt](https://github.com/gamcil/clinker/files/10330660/DSM17330.txt)
Hi Cameron and Happy New Year, here attached two examples files from RAST annotation plateform. I have solved the problem using Prokka .gbf output files. If you can see what is it wrong. And what about the update to v0.0.28

Sincerely

Olivier

**Comment by gamcil** [comment]
Hi Olivier, sorry for the delay. It looks like the aligner is getting tripped up by lowercase letters in some protein translations - will add a fix for this in the next release.
